### ISSUE TITLE
Too many values to unpack, missing return variable for query_rbf

### ISSUE THREAD

**Issue by asaran** [Pearl-UTexas/ActiveVaR#1]
https://github.com/Pearl-UTexas/ActiveVaR/blob/2ab212e05da81c6e9c4e5ea71c3b932d7e318504/placeTable/place_flowers_softmax#L144

**Comment by yuchen93** [comment]
Fixed by commit [7445048](https://github.com/Pearl-UTexas/ActiveVaR/commit/7445048397fdba22e5493e89ce22174efc15f883)
